# Change these first
owner: wonoly # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main website
    url: https://wonoly.net
  - name: Search website
    url: https://search.wonoly.net
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  cname: status.wonoly.net


  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/83232058
  name: "Wonoly's upptime"
  introTitle: "**Wonoly's Upptime** is the uptime monitor and status page for Wonoly."
  introMessage: "This is wonoly's upptime, you can see where a service is working or not and their incidents."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
